# Install script for directory: C:/Users/maxbe/Documents/Swat3/skylicht-engine

# Set the install prefix
if(NOT DEFINED CMAKE_INSTALL_PREFIX)
  set(CMAKE_INSTALL_PREFIX "C:/Users/maxbe/Documents/Swat3/skylicht-engine/InstallLibs")
endif()
string(REGEX REPLACE "/$" "" CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")

# Set the install configuration name.
if(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)
  if(BUILD_TYPE)
    string(REGEX REPLACE "^[^A-Za-z0-9_]+" ""
           CMAKE_INSTALL_CONFIG_NAME "${BUILD_TYPE}")
  else()
    set(CMAKE_INSTALL_CONFIG_NAME "Release")
  endif()
  message(STATUS "Install configuration: \"${CMAKE_INSTALL_CONFIG_NAME}\"")
endif()

# Set the component getting installed.
if(NOT CMAKE_INSTALL_COMPONENT)
  if(COMPONENT)
    message(STATUS "Install component: \"${COMPONENT}\"")
    set(CMAKE_INSTALL_COMPONENT "${COMPONENT}")
  else()
    set(CMAKE_INSTALL_COMPONENT)
  endif()
endif()

# Is this installation the result of a crosscompile?
if(NOT DEFINED CMAKE_CROSSCOMPILING)
  set(CMAKE_CROSSCOMPILING "FALSE")
endif()

if(NOT CMAKE_INSTALL_LOCAL_ONLY)
  # Include the install script for each subdirectory.
  include("C:/Users/maxbe/Documents/Swat3/skylicht-engine/BuildCommand/Projects/ThirdParty/cmake_install.cmake")
  include("C:/Users/maxbe/Documents/Swat3/skylicht-engine/BuildCommand/Projects/Irrlicht/cmake_install.cmake")
  include("C:/Users/maxbe/Documents/Swat3/skylicht-engine/BuildCommand/Projects/Skylicht/System/cmake_install.cmake")
  include("C:/Users/maxbe/Documents/Swat3/skylicht-engine/BuildCommand/Projects/Skylicht/Engine/cmake_install.cmake")
  include("C:/Users/maxbe/Documents/Swat3/skylicht-engine/BuildCommand/Projects/Imgui/cmake_install.cmake")
  include("C:/Users/maxbe/Documents/Swat3/skylicht-engine/BuildCommand/Projects/SpineCpp/cmake_install.cmake")
  include("C:/Users/maxbe/Documents/Swat3/skylicht-engine/BuildCommand/Projects/Skylicht/Components/cmake_install.cmake")
  include("C:/Users/maxbe/Documents/Swat3/skylicht-engine/BuildCommand/Projects/Skylicht/Collision/cmake_install.cmake")
  include("C:/Users/maxbe/Documents/Swat3/skylicht-engine/BuildCommand/Projects/Skylicht/Lightmapper/cmake_install.cmake")
  include("C:/Users/maxbe/Documents/Swat3/skylicht-engine/BuildCommand/Projects/Bullet3/cmake_install.cmake")
  include("C:/Users/maxbe/Documents/Swat3/skylicht-engine/BuildCommand/Projects/Skylicht/Physics/cmake_install.cmake")
  include("C:/Users/maxbe/Documents/Swat3/skylicht-engine/BuildCommand/Projects/Skylicht/Audio/cmake_install.cmake")
  include("C:/Users/maxbe/Documents/Swat3/skylicht-engine/BuildCommand/Projects/Skylicht/UserInterface/cmake_install.cmake")
  include("C:/Users/maxbe/Documents/Swat3/skylicht-engine/BuildCommand/Projects/Skylicht/Crypto/cmake_install.cmake")
  include("C:/Users/maxbe/Documents/Swat3/skylicht-engine/BuildCommand/Projects/Skylicht/Network/cmake_install.cmake")
  include("C:/Users/maxbe/Documents/Swat3/skylicht-engine/BuildCommand/Projects/Skylicht/Client/cmake_install.cmake")
  include("C:/Users/maxbe/Documents/Swat3/skylicht-engine/BuildCommand/Projects/EditorGUI/cmake_install.cmake")
  include("C:/Users/maxbe/Documents/Swat3/skylicht-engine/BuildCommand/Projects/Editor/cmake_install.cmake")
  include("C:/Users/maxbe/Documents/Swat3/skylicht-engine/BuildCommand/Samples/Animations/cmake_install.cmake")
  include("C:/Users/maxbe/Documents/Swat3/skylicht-engine/BuildCommand/Samples/Audio/cmake_install.cmake")
  include("C:/Users/maxbe/Documents/Swat3/skylicht-engine/BuildCommand/Samples/BlendShape/cmake_install.cmake")
  include("C:/Users/maxbe/Documents/Swat3/skylicht-engine/BuildCommand/Samples/BoidSystem/cmake_install.cmake")
  include("C:/Users/maxbe/Documents/Swat3/skylicht-engine/BuildCommand/Samples/BoidSystemVAT/cmake_install.cmake")
  include("C:/Users/maxbe/Documents/Swat3/skylicht-engine/BuildCommand/Samples/Collision/cmake_install.cmake")
  include("C:/Users/maxbe/Documents/Swat3/skylicht-engine/BuildCommand/Samples/DrawPrimitives/cmake_install.cmake")
  include("C:/Users/maxbe/Documents/Swat3/skylicht-engine/BuildCommand/Samples/GUI/cmake_install.cmake")
  include("C:/Users/maxbe/Documents/Swat3/skylicht-engine/BuildCommand/Samples/HelloWorld/cmake_install.cmake")
  include("C:/Users/maxbe/Documents/Swat3/skylicht-engine/BuildCommand/Samples/SCNEdit/cmake_install.cmake")
  include("C:/Users/maxbe/Documents/Swat3/skylicht-engine/BuildCommand/Samples/Instancing/cmake_install.cmake")
  include("C:/Users/maxbe/Documents/Swat3/skylicht-engine/BuildCommand/Samples/LuckyDraw/cmake_install.cmake")
  include("C:/Users/maxbe/Documents/Swat3/skylicht-engine/BuildCommand/Samples/OcclusionQuery/cmake_install.cmake")
  include("C:/Users/maxbe/Documents/Swat3/skylicht-engine/BuildCommand/Samples/PBR/cmake_install.cmake")
  include("C:/Users/maxbe/Documents/Swat3/skylicht-engine/BuildCommand/Samples/CharacterController/cmake_install.cmake")
  include("C:/Users/maxbe/Documents/Swat3/skylicht-engine/BuildCommand/Samples/LoadScene/cmake_install.cmake")
  include("C:/Users/maxbe/Documents/Swat3/skylicht-engine/BuildCommand/Samples/Physics/cmake_install.cmake")
  include("C:/Users/maxbe/Documents/Swat3/skylicht-engine/BuildCommand/Samples/SkinnedMesh/cmake_install.cmake")
  include("C:/Users/maxbe/Documents/Swat3/skylicht-engine/BuildCommand/Samples/SkinnedMeshInstancing/cmake_install.cmake")
  include("C:/Users/maxbe/Documents/Swat3/skylicht-engine/BuildCommand/Samples/Spine2D/cmake_install.cmake")
  include("C:/Users/maxbe/Documents/Swat3/skylicht-engine/BuildCommand/Samples/Sponza/cmake_install.cmake")
  include("C:/Users/maxbe/Documents/Swat3/skylicht-engine/BuildCommand/Samples/SpringBone/cmake_install.cmake")
  include("C:/Users/maxbe/Documents/Swat3/skylicht-engine/BuildCommand/Samples/TankScene/cmake_install.cmake")
  include("C:/Users/maxbe/Documents/Swat3/skylicht-engine/BuildCommand/Samples/WalkIK/cmake_install.cmake")
  include("C:/Users/maxbe/Documents/Swat3/skylicht-engine/BuildCommand/Samples/Lightmap/cmake_install.cmake")
  include("C:/Users/maxbe/Documents/Swat3/skylicht-engine/BuildCommand/Samples/Lightmapping/cmake_install.cmake")
  include("C:/Users/maxbe/Documents/Swat3/skylicht-engine/BuildCommand/Samples/LightmappingDirectional/cmake_install.cmake")
  include("C:/Users/maxbe/Documents/Swat3/skylicht-engine/BuildCommand/Samples/LightmappingVertex/cmake_install.cmake")
  include("C:/Users/maxbe/Documents/Swat3/skylicht-engine/BuildCommand/Samples/LightmapUV/cmake_install.cmake")
  include("C:/Users/maxbe/Documents/Swat3/skylicht-engine/BuildCommand/Samples/Materials/cmake_install.cmake")
  include("C:/Users/maxbe/Documents/Swat3/skylicht-engine/BuildCommand/Samples/Noise2D/cmake_install.cmake")
  include("C:/Users/maxbe/Documents/Swat3/skylicht-engine/BuildCommand/Samples/Noise3D/cmake_install.cmake")
  include("C:/Users/maxbe/Documents/Swat3/skylicht-engine/BuildCommand/Samples/Particles/cmake_install.cmake")
  include("C:/Users/maxbe/Documents/Swat3/skylicht-engine/BuildCommand/Samples/ParticlesVortex/cmake_install.cmake")
  include("C:/Users/maxbe/Documents/Swat3/skylicht-engine/BuildCommand/Samples/ParticlesExplosion/cmake_install.cmake")
  include("C:/Users/maxbe/Documents/Swat3/skylicht-engine/BuildCommand/Samples/ParticlesMagicSkill/cmake_install.cmake")
  include("C:/Users/maxbe/Documents/Swat3/skylicht-engine/BuildCommand/Samples/Shader/cmake_install.cmake")
  include("C:/Users/maxbe/Documents/Swat3/skylicht-engine/BuildCommand/Samples/SocketIO/cmake_install.cmake")
  include("C:/Users/maxbe/Documents/Swat3/skylicht-engine/BuildCommand/UnitTest/TestApp/cmake_install.cmake")

endif()

string(REPLACE ";" "\n" CMAKE_INSTALL_MANIFEST_CONTENT
       "${CMAKE_INSTALL_MANIFEST_FILES}")
if(CMAKE_INSTALL_LOCAL_ONLY)
  file(WRITE "C:/Users/maxbe/Documents/Swat3/skylicht-engine/BuildCommand/install_local_manifest.txt"
     "${CMAKE_INSTALL_MANIFEST_CONTENT}")
endif()
if(CMAKE_INSTALL_COMPONENT)
  if(CMAKE_INSTALL_COMPONENT MATCHES "^[a-zA-Z0-9_.+-]+$")
    set(CMAKE_INSTALL_MANIFEST "install_manifest_${CMAKE_INSTALL_COMPONENT}.txt")
  else()
    string(MD5 CMAKE_INST_COMP_HASH "${CMAKE_INSTALL_COMPONENT}")
    set(CMAKE_INSTALL_MANIFEST "install_manifest_${CMAKE_INST_COMP_HASH}.txt")
    unset(CMAKE_INST_COMP_HASH)
  endif()
else()
  set(CMAKE_INSTALL_MANIFEST "install_manifest.txt")
endif()

if(NOT CMAKE_INSTALL_LOCAL_ONLY)
  file(WRITE "C:/Users/maxbe/Documents/Swat3/skylicht-engine/BuildCommand/${CMAKE_INSTALL_MANIFEST}"
     "${CMAKE_INSTALL_MANIFEST_CONTENT}")
endif()
